# Generated by Django 4.2.4 on 2023-08-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("priorities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priority",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
