# Generated by Django 4.1.7 on 2023-08-28 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("priorities", "0002_alter_priority_order"),
        ("tasks", "0002_task_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="priorities.priority",
            ),
            preserve_default=False,
        ),
    ]
