# Generated by Django 4.1.7 on 2023-08-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
