# Generated by Django 4.2.4 on 2023-08-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0002_status_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
